# Generated by Django 4.2.9 on 2024-08-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
