# Generated by Django 4.2.5 on 2023-10-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='todolist',
            name='surname',
            field=models.CharField(default='example', max_length=200),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(default='example', max_length=200),
        ),
    ]
