# Generated by Django 4.2.5 on 2023-10-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_todolist_email_todolist_surname_alter_todolist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='avatar',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='todolist',
            name='message',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
