# Generated by Django 4.2.5 on 2023-11-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_todolist_avatar_todolist_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='surname',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
