# Generated by Django 4.2.9 on 2024-08-03 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
