# Generated by Django 4.2.9 on 2024-08-03 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
